name = "schedule"
workers_dev = true
compatibility_date = "2024-03-28"
main = "./_build/default/bin/node/bin/main.js"
vars = { DISABLE_CORS = "false" }
routes = [
  { pattern = "schedule.adrianpar.vin/api/*", zone_name = "adrianpar.vin" },
]

[ai]
binding = "ai" 

[build]
command = "dune build"
watch_dir = "bin"

